### ISSUE TITLE
InsideGeofenceStartDebounceTime functionality

### ISSUE THREAD

**Issue by brabiega** [afarran/swm2m_vms_tests#38]
Currently GeofenceEntry from mobile message is sent without debounce time (InsideGeofenceStartDebounceTime) taken under consideration. 

Example:

> InsideGeofenceStartDebounceTime is set to 20 seconds
> Geofence interval = 10, hysteresis = 0
> Terminal goes inside geofence Zone
> Geofences are recalculated after geofence interval + hysteresis
> GeofenceEntry is sent immediately without 20 seconds debounce time

Is it correct?

The documentation says that debounce time affects only InsideGeofence state.

I find it a little bit confusing, because user may receive GeofenceEntry message, while InsideGeofence stat is false.

**Comment by afarran** [comment]
Yes this is correct. Geofence Entry/Exit messages are not the same as "Abnormal" events/messages. The Abnormal InsideGeofence debounce time is in addition to the geofence core service interval/hysteresis time by design. By setting this InsideGeofence debounce time to zero (i.e. default) you'd achieve a state match between Geofence Entry/Exit and the InsideGeofence state.

PS. When you label an issue as a bug, please state what the expected behaviour is.

**Comment by brabiega** [comment]
PS. When you label an issue as a bug, please state what the expected behaviour is.
- Will do.

Thanks for explanation.
