### ISSUE TITLE
rs232mainDTEIsConnected property (PIN7) in serial service (SIN22) is not changing when DTECONNECTED event is posted

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_vms_tests#39]
According to T202, event "DTECONNECTED" is:
_Event posted that a DTE device has been either connected or disconnected from the RS-232 port._ 
For this moment DTECONNECTED with argument true or false does not affect rs232mainDTEIsConnected property (PIN7) in serial service (SIN22) - it stays in state 'false'.

This property is being monitored by VMS agent and according to it's changes AbnormalReport with  HwClientDisconnected information should be sent. 

Steps to reproduce:
1. Check the value of the PIN7 in SIN22 
2. Depending on the the state read in point#1 post an event to change it - send shell command to execute following lua code: `sched.post("_RS232","DTECONNECTED",true)`
3. Check the state of the  PIN7 in SIN22  - it does not change. 

Expected behaviour:  DTECONNECTED changes state of PIN7 in SIN22.

Triggering VMS AbnormalReport with HwClientDisconnected information is not possible this way.

Question: Is the behaviour rs232mainDTEIsConnected property (PIN7) in serial service (SIN22) correct? Or is there any other trigger required to change it's value? 

Related TC: 
test_HwClientDisconnected_ForTerminalInHwClientDisconnectedStateTrueWhenHwClientIsConnectedForTimeAboveHwClientDisconnectedEndDebounceTime_HwClientDisconnectedAbnormalReportIsSent

Lua Services Framework  Version: 9.0.10,  Package version: 5.0.10.9363

Note1:
SIN=22(serial) PIN=10(rs232mainDTEEdgeDetect) **is set to** val=Both

**Comment by afarran** [comment]
Posting the event does not change the property value. The property value changes and the event is posted when the DTE connection status changes (e.g. someone disconnects/reconnects the the physical RS232 port from the terminal).

Posting the event manually is an attempt to simulate that physical action. It should also be accompanied by simulating the property value as well. Check with Bartosz and Pawel to see if there's a way to override/fake this property for testing purposes. Otherwise this test cannot be fully automated.

**Comment by brabiega** [comment]
This chunk should do the magic

```
serialDTEConnected = true
oldSerialOnGetVolatile = svc.serial.onGetVolatile
svc.serial.onGetVolatile = function(pin, name)
  if pin == 7 then 
    return serialDTEConnected
  else
    oldSerialOnGetVolatile(pin, name)
  end
end
```

**Comment by ArturMalyszewicz** [comment]
Solution provided by Bartosz is working fine. TCs have been updated.
